#ifndef _APPLICATION_H
#define _APPLICATION_H

#ifndef VERSION
#define VERSION "0.2"
#endif

#include <twr.h>
#include <bcl.h>

typedef struct {
   uint64_t  SERVICE_INTERVAL_INTERVAL;
   uint64_t  BATTERY_UPDATE_INTERVAL;
   uint64_t  UPDATE_SERVICE_INTERVAL;      
   uint64_t  UPDATE_NORMAL_INTERVAL;
   uint64_t  BAROMETER_UPDATE_SERVICE_INTERVAL;
   uint64_t  BAROMETER_UPDATE_NORMAL_INTERVAL;
   uint64_t  TEMPERATURE_TAG_PUB_NO_CHANGE_INTEVAL;
   uint64_t  TEMPERATURE_TAG_PUB_VALUE_CHANGE;
   uint64_t  HUMIDITY_TAG_PUB_NO_CHANGE_INTEVAL;
   uint64_t  HUMIDITY_TAG_PUB_VALUE_CHANGE;
   uint64_t  LUX_METER_TAG_PUB_NO_CHANGE_INTEVAL;
   uint64_t  LUX_METER_TAG_PUB_VALUE_CHANGE;
   uint64_t  BAROMETER_TAG_PUB_NO_CHANGE_INTEVAL;
   uint64_t  BAROMETER_TAG_PUB_VALUE_CHANGE;
} all_settings_t;

#endif
