#ifndef _APPLICATION_H
#define _APPLICATION_H

#include <twr.h>
#include <bcl.h>

typedef struct
{
    uint8_t channel;
    float value;
    twr_tick_t next_pub;

} event_param_t;

typedef struct {
    uint32_t  SERVICE_INTERVAL_INTERVAL;
    uint32_t  BATTERY_UPDATE_INTERVAL;
    uint32_t  UPDATE_SERVICE_INTERVAL;      
    uint32_t  UPDATE_NORMAL_INTERVAL;
    uint32_t  BAROMETER_UPDATE_SERVICE_INTERVAL;
    uint32_t  BAROMETER_UPDATE_NORMAL_INTERVAL;
    uint32_t  TEMPERATURE_UPDATE_SERVICE_INTERVAL;
    uint32_t  TEMPERATURE_UPDATE_NORMAL_INTERVAL;
    uint32_t  HUMIDITY_UPDATE_SERVICE_INTERVAL;
    uint32_t  HUMIDITY_UPDATE_NORMAL_INTERVAL;
    uint32_t  LUX_METER_UPDATE_SERVICE_INTERVAL;
    uint32_t  LUX_METER_UPDATE_NORMAL_INTERVAL;
    uint32_t  CO2_UPDATE_SERVICE_INTERVAL;
    uint32_t  CO2_UPDATE_NORMAL_INTERVAL;
    uint32_t  VOC_LP_UPDATE_SERVICE_INTERVAL;
    uint32_t  VOC_LP_UPDATE_NORMAL_INTERVAL;
    uint32_t  TEMPERATURE_TAG_PUB_NO_CHANGE_INTERVAL;
    float_t TEMPERATURE_TAG_PUB_VALUE_CHANGE;
    uint32_t  HUMIDITY_TAG_PUB_NO_CHANGE_INTERVAL;
    float_t  HUMIDITY_TAG_PUB_VALUE_CHANGE;
    uint32_t  LUX_METER_TAG_PUB_NO_CHANGE_INTERVAL;
    float_t  LUX_METER_TAG_PUB_VALUE_CHANGE;
    uint32_t  BAROMETER_TAG_PUB_NO_CHANGE_INTERVAL;
    float_t  BAROMETER_TAG_PUB_VALUE_CHANGE;
    uint32_t BUTTON_SCAN_INTERVAL;
    uint32_t BUTTON_DEBOUNCE_TIME;
    uint32_t BUTTON_CLICK_TIMEOUT;
    uint32_t BUTTON_HOLD_TIME;
} all_settings_t;

#endif
 